# Generated by Django 6.0.7 on 2026-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_p', models.CharField(max_length=50)),
                ('prix', models.PositiveIntegerField()),
                ('qte', models.PositiveIntegerField()),
            ],
        ),
    ]
