# Generated by Django 6.0.7 on 2026-07-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='date_insert',
            field=models.DateField(null=True),
        ),
    ]
