# Generated by Django 6.0.7 on 2026-07-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_produits_date_insert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produits',
            options={'ordering': ['nom_p']},
        ),
    ]
